### ISSUE TITLE
Add rotation

### ISSUE THREAD

**Issue by Blackcipher101** [Blackcipher101/CamScanner_webapp#10]
Use OpenCV to add rotation

**Comment by Gaurav7888** [comment]
I want to work upon this issue , i had experienced  using opencv .

**Comment by Blackcipher101** [comment]
You can start so try adding rotation page just after cropping. In which the user can rotate the image to the right orentation

**Comment by Gaurav7888** [comment]
@Blackcipher101  okay after cropping  func i will add my rotn function. Thx for assigning!
