### ISSUE TITLE
add a .gitignore

### ISSUE THREAD

**Issue by Blackcipher101** [Blackcipher101/CamScanner_webapp#14]
added a gitignore so that unnecessary pycache won't get commited

**Comment by yashvarshney003** [comment]
ok

**Comment by Blackcipher101** [comment]
Would you like to do this issue?

**Comment by Blackcipher101** [comment]
Would you like to do this issue

**Comment by Blackcipher101** [comment]
Make sure you always link the issue in your PR so it can directly close it

**Comment by yashvarshney003** [comment]
Ok.
