### ISSUE TITLE
add a link to documentation to this Repo

### ISSUE THREAD

**Issue by Blackcipher101** [Blackcipher101/CamScanner_webapp#2]
Add the link to Documentation to this Repo

**Comment by yashvarshney003** [comment]
Can you give please elaborate?

**Comment by Blackcipher101** [comment]
there is already a <a> tag just send it to this readme link.

**Comment by nonlinearjunkie** [comment]
@Blackcipher101 can you assign this task to me?

**Comment by Blackcipher101** [comment]
ok @surajzep, @yashvarshney003 you can try something else as this a very beginner friendly issue and you have already contributed to the code

**Comment by yashvarshney003** [comment]
@Blackcipher101  
ok

**Comment by Blackcipher101** [comment]
@surajzep any progress

**Comment by Blackcipher101** [comment]
@surajzep I will unassign the issue in 1 day if I don't see any communictation

**Comment by nonlinearjunkie** [comment]
@Blackcipher101  sorry bro was quite busy due to college deadlines!! Will push the changes tomorrow!!

**Comment by Blackcipher101** [comment]
> @Blackcipher101 sorry bro was quite busy due to college deadlines!! Will push the changes tomorrow!!

No issues just communicate.

**Comment by nonlinearjunkie** [comment]
@Blackcipher101  can I create a base HTML file with header HTML code and link it to every HTML file where we need header so that if we make a change in the base file it would get reflected in all pages?

**Comment by Blackcipher101** [comment]
We can we will need to use Django ability to extend templates
If you interested make an issue and close this one

**Comment by nonlinearjunkie** [comment]
@Blackcipher101  okay!

**Comment by nonlinearjunkie** [comment]
@Blackcipher101 I can't see the option for closing the issue in my view..you can close it...I will create a new one!

**Comment by Blackcipher101** [comment]
Ok I will close this
